### ISSUE TITLE
About Page profiles

### ISSUE THREAD

**Issue by r-southworth** [datagrovecr/website#7]
I think it might be somewhat confusing and also murky on the legal side to have Jim on the Datagrove CR page. I think we are better off linking to the Datagrove page and putting a profile for him there if we want to have a profile out there.

I think labeling Tomas/Chelsea as "Educator" might be confusing these profiles should highlight their roles in Datagrove Costa Rica, maybe get rid of the subtext for now, and have them write a blurb about why/how they got involved in Datagrove Costa Rica.

Add interns and employees as we get them.

**Comment by meagan13** [comment]
Jim removed and Chelsea and Tomás bios removed for now
